import Foundation

print("Running ColimaBar tests...\n")

test_parseListJSON_running()
test_parseListJSON_stopped()
test_parseListJSON_invalid_returnsNil()
test_memoryGB_conversion()
test_portainerExists_found()
test_portainerExists_notFound()
test_fetchStateSync_running_portainerExists()
test_fetchStateSync_running_portainerMissing()
test_fetchStateSync_stopped_skipsDockerCheck()
test_fetchStateSync_invalidJSON_returnsUnknown()
test_colimaConfig()
test_parseDockerContainers_multiLine()
test_parseDockerContainers_running()
test_parseDockerContainers_exited()
test_parseDockerContainers_empty()
test_fetchStateSync_running_includesContainers()
test_fetchStateSync_stopped_noContainers()
test_colimaProfiles_presets()
test_colimaProfiles_activeMatch()
test_health_healthy()
test_health_unhealthy()
test_health_starting()
test_health_nil_no_healthcheck()
test_hostPortNumbers_single()
test_hostPortNumbers_multiple()
test_hostPortNumbers_empty()
test_parseDockerImages_singleLine()
test_parseDockerImages_multiLine()
test_parseDockerImages_empty()
test_parseDockerVolumes_countAndNames()
test_parseDockerVolumes_driverAndSize()
test_parseDockerVolumes_sizeNA_whenDfMissing()
test_parseDockerVolumes_empty()

print("\n\(_passed) passed, \(_failed) failed")
if _failed > 0 {
    exit(1)
}
